# Generated by Django 2.2.3 on 2019-07-22 06:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Date',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.IntegerField(default=1)),
                ('start_time', models.IntegerField(default=0)),
                ('end_time', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vim', models.BooleanField(default=False)),
                ('board', models.BooleanField(default=False)),
                ('desk', models.BooleanField(default=False)),
                ('multitap', models.IntegerField(default=0)),
                ('speaker', models.BooleanField(default=False)),
                ('lights', models.BooleanField(default=False)),
                ('mirror', models.BooleanField(default=False)),
                ('aircomditioner', models.BooleanField(default=False)),
                ('printer', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Purpose_category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('study', models.BooleanField(default=False)),
                ('performance', models.BooleanField(default=False)),
                ('practice', models.BooleanField(default=False)),
                ('conference', models.BooleanField(default=False)),
                ('etc', models.BooleanField(default=False)),
                ('etc_what', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Qna',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('confirm', models.BooleanField(default=False)),
                ('context', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('nickname', models.CharField(max_length=10)),
                ('area', models.CharField(max_length=10)),
                ('report_count', models.IntegerField(default=0)),
                ('podo', models.IntegerField(default=10)),
                ('gender', models.BooleanField(default=False)),
                ('image', models.FileField(blank=True, null=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('text', models.TextField(null=True)),
                ('image', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='main.Image')),
                ('like', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='main.Like')),
                ('user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='main.User')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('location', models.CharField(max_length=100)),
                ('price', models.IntegerField(max_length=999999)),
                ('hit_count', models.IntegerField(default=0)),
                ('category', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='main.Purpose_category')),
                ('date', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='main.Date')),
                ('image', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='main.Image')),
                ('like', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='main.Like')),
                ('option', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='main.Option')),
                ('qna', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='main.Qna')),
                ('review', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='main.Review')),
            ],
        ),
        migrations.AddField(
            model_name='like',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='main.User'),
        ),
    ]
